"""Generate immutable Dart response DTOs from the implemented OpenAPI contract.

No network/toolchain dependency. Fail on unsupported schema shapes, never guess.
Nested free-form/manual literal snapshots remain JSON maps intentionally.
"""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NAMES = ("MedicationView", "OccurrenceView", "HistoryView", "PreviewView")


def shape(schema):
    nullable = False
    if "anyOf" in schema:
        choices = [s for s in schema["anyOf"] if s.get("type") != "null"]
        if len(choices) != 1:
            raise ValueError("Unsupported union")
        nullable = len(choices) != len(schema["anyOf"])
        schema = choices[0]
    types = {
        "string": "String",
        "integer": "int",
        "boolean": "bool",
        "number": "num",
        "object": "Map<String, dynamic>",
    }
    if "$ref" in schema:
        result = "Map<String, dynamic>"
    elif schema.get("type") == "array":
        result = f"List<{shape(schema['items'])[0]}>"
    else:
        result = types[schema["type"]]
    return result + ("?" if nullable else ""), schema


def generate():
    schemas = json.loads((ROOT / "contracts/openapi.json").read_text())["components"]["schemas"]
    lines = ["// Generated by scripts/generate_manual_client.py. Do not edit.", ""]
    for name in NAMES:
        fields = []
        for wire, schema in schemas[name]["properties"].items():
            dart = wire.split("_")[0] + "".join(p.title() for p in wire.split("_")[1:])
            type_, _ = shape(schema)
            fields.append((wire, dart, type_))
        lines += [
            f"class {name} {{",
            f"  const {name}({{",
            *[f"    required this.{dart}," for _, dart, _ in fields],
            "  });",
        ]
        lines += [f"  final {type_} {dart};" for _, dart, type_ in fields]
        lines += [f"  factory {name}.fromJson(Map<String, dynamic> json) => {name}("]
        for wire, dart, type_ in fields:
            expr = f"json['{wire}'] as {type_}"
            if type_.startswith("List<"):
                inner = type_[5:-1]
                expr = f"(json['{wire}'] as List).cast<{inner}>()"
            lines.append(f"    {dart}: {expr},")
        lines += ["  );", "}", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = ROOT / "apps/medlm/lib/medications/generated/manual_models.dart"
    content = generate()
    if args.check:
        if not path.exists() or path.read_text() != content:
            raise SystemExit("Manual client bindings are stale")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
